# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: "MemCheck build and deploy to Azure"

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: "MemCheck compilation and deployment to prod"

    runs-on: windows-latest

    env:
      NETCORE_VERSION: "3.1.103"
      COMPIL_CONFIG: "Release"
      PUBLISH_FOLDER: "./Published"
      AZURE_APP_NAME: "memcheckfr"

    steps:
    - uses: actions/checkout@v2

    - name: "Set up .NET Core on machine (version ${{env.NETCORE_VERSION}})"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.NETCORE_VERSION}}

    - name: "Restore NuGet packages"
      run: dotnet restore

    - name: "Build the root sln with dotnet"
      run: dotnet build --no-restore --configuration ${{env.COMPIL_CONFIG}}

    - name: "Publish: prepare the packages to deploy"
      run: dotnet publish --no-build --configuration ${{env.COMPIL_CONFIG}} -o ${{env.PUBLISH_FOLDER}}

    - name: "Deploy to MemCheck Azure Web App"
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{env.AZURE_APP_NAME}}'
        slot-name: 'production'
        publish-profile: ${{secrets.MEMCHECK_PUBLISH_PROFILE}}
        package: ${{env.PUBLISH_FOLDER}}
